### ISSUE TITLE
Update pom dependency version for develop branch

### ISSUE THREAD

**Issue by abhi-mshetti** [opencb/biodata#102]
I was trying to work with the `develop` version of OpenCGA and noticed that there is conflict for the versions for ga4gh in the pom file on this project. Can we get that upgraded to 0.6.0a5? 

Thanks

**Comment by j-coll** [comment]
Correct, the ga4gh repository was updated few days ago, but not the biodata dependency, which has all the utilities.

In that ga4gh version, all the models has been ported to proto. We will continue supporting Avro models, but also proto support is needed.

I will upgrade the dependency.

**Comment by abhi-mshetti** [comment]
Thanks!
