### ISSUE TITLE
How to get a valid version?

### ISSUE THREAD

**Issue by renyaoxiang** [opencb/biodata#156]
I cloned the project in my pc, and there are some errors. 
How could I get the valid version code?

**Comment by j-coll** [comment]
Which error are you getting? Which branch are you compiling?

**Comment by renyaoxiang** [comment]
Develop, master and release are all making errors while compiling.
It is because of some missing classes. Some missing class list as follows:
```
org.opencb.biodata.models.variant.avro.AlternateCoordinate;
org.opencb.biodata.models.variant.avro.FileEntry;
org.opencb.biodata.models.variant.avro.VariantAnnotation;
```

**Comment by renyaoxiang** [comment]
I also admier to be a contributer of opencb.
How and what should I do?

**Comment by j-coll** [comment]
How did you tried to compile?

It seems that you mvn didn't execute the "generate-sources" step to generate those files from the avdl.

Try `mvn clean install -DskipTests`

**Comment by renyaoxiang** [comment]
Thank you , it works.

**Comment by renyaoxiang** [comment]
I admier to be a contributer for opencb.
Could I have you some suggestions?

**Comment by imedina** [comment]
Hi,
sorry I think I missed your message!
Many thanks for your comments, sure you can please! We can have a private conversation if you wish.

**Comment by renyaoxiang** [comment]
I am glad to hear from you. I would send a email latter.
