### ISSUE TITLE
Support for multi-allelic variants

### ISSUE THREAD

**Issue by cyenyxe** [opencb/biodata#17]
At the moment, we lose some information when we transform variants with more than one alternate. 

A list of "secondary alternates" must be added to the VariantSourceEntry class, and all genotypes of a VCF line will be saved in that entry. The allele indexes in the genotypes must be changed to represent the main and secondary alternates properly.

Example:

Start | Ref | Alternates | Genotypes
------ | ----- | ------ | --------------
1000 | A | C, T, G | 1/0    1/1    0/2    1/3

Will be transformed into:

Start | Ref | Main alt | Secondary alts | Genotypes
------ | ----- | ------ | ------------- | --------------
1000 | A | C | T, G | 1/0    1/1    0/2    1/3
1000 | A | T | C, G | 2/0    2/2    0/1    2/3
1000 | A | G | C, T | 2/0    2/2    0/3    2/1

**Comment by imedina** [comment]
Moving this issue to next release since it may need some more time to be finished and tested

**Comment by cyenyxe** [comment]
Has the representation of multi-allelic VCF lines mixing SNPs and INDELs with actual different starting positions been fixed?
