### ISSUE TITLE
VariantStats can have incorrect (null) values leading to wrong VariantGlobalStats

### ISSUE THREAD

**Issue by jmmut** [opencb/biodata#30]
In opencga, the converters call to the empty constructor of `VariantStats` leaving `refAllele`, `altAllele` and `Type` to default values. When calling `VariantGlobalStats.update()` from `VariantSourceStats.updateFileStats()`, a `NullPointerException` raises (for each VariantStats read from mongo).

As the setters are package-protected, they can not be set afterwards, and as the converters inherit their prototypes, they can not accept a `Variant` to construct the `VariantStats` with.

How can we solve it? proposals:
- converters shouldn't inherit fixed prototypes.
- public setters.

**Comment by jmmut** [comment]
Of course, allowing those fields to be null, raises errors in more places, like `VariantToDBObjectConverter`.

**Comment by j-coll** [comment]
All getters and setters are public since e044018d7a90ea61cabf7f047517528618be9973
