### ISSUE TITLE
Remove System.exit() at fail

### ISSUE THREAD

**Issue by j-coll** [opencb/biodata#42]
There are some `System.exit()` as a result of unexpected states, like missing the VariantHeader. They should be replaced with a more accurate management.

[VariantVcfReader.java : 254](https://github.com/opencb/biodata/blob/develop/biodata-formats/src/main/java/org/opencb/biodata/formats/variant/vcf4/io/VariantVcfReader.java#L254)
[VcfRawReader.java : 260](https://github.com/opencb/biodata/blob/develop/biodata-formats/src/main/java/org/opencb/biodata/formats/variant/vcf4/io/VcfRawReader.java#L260)
[VepFormatReader.java : 396](https://github.com/opencb/biodata/blob/develop/biodata-formats/src/main/java/org/opencb/biodata/formats/annotation/io/VepFormatReader.java#L396)
[VepFormatReader.java : 414](https://github.com/opencb/biodata/blob/develop/biodata-formats/src/main/java/org/opencb/biodata/formats/annotation/io/VepFormatReader.java#L414)

**Comment by cyenyxe** [comment]
But now the system simply accepts badly formed files...
I am not saying that those System.exit were a good idea, but the error should be raised and let the library users decide if they want to stop the processing or not.

**Comment by imedina** [comment]
Libraries should throw an exception instead of calling to System.exit, those classes need some work and authors should fix them. At least now Tomcats do not crash now.
